# Generated by Django 6.0.7 on 2026-07-26 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('operation_type', models.CharField(choices=[('write_off', 'Списание'), ('arrival', 'Поступление'), ('adjustment', 'Корректировка')], default='write_off', max_length=20, verbose_name='Тип операции')),
                ('idempotency_key', models.CharField(blank=True, help_text='Позволяет избежать дублирования операций при повторных запросах.', max_length=64, null=True, verbose_name='Ключ идемпотентности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='products.equipment', verbose_name='Оборудование')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция по складу',
                'verbose_name_plural': 'Операции по складу',
                'indexes': [models.Index(fields=['idempotency_key'], name='products_st_idempot_d1f594_idx')],
            },
        ),
    ]
